#!/bin/bash

# M modified
# R renamed
# A added
# C copied
files_to_edit_copyright=$(git diff --cached --name-only --diff-filter=MARC)
cur_year=$(date +"%Y")

if [[ ! -z $files_to_edit_copyright ]]; then
	echo "In the following files 'copyright' is not actual:"
fi

for file in $files_to_edit_copyright
do

	grep -iq $cur_year -m1 <(sed -n '1,3p' $file)
	exit_status=$?

	if [[ $exit_status -ne 0 ]]; then
		echo "  $file"

		# replace year "before"
		# YYYY_from - YYYY_to => YYYY_from - actual_YYYY_to
		sed -i -E '1,3 s/(20[0-9]{2})\s*-\s*(20[0-9]{2})/\1 - '$cur_year'/g' $file

		# if it finds the current year - the replacement has been made OR the current year
		# has already been => the next replacement command is not necessary
		grep -iq $cur_year -m1 <(sed -n '1,3p' $file)
		exit_status=$?

		# else
		if [[ $exit_status -ne 0 ]]; then
	        	# yyyy_from => yyyy_from - yyyy_to
			sed -i -E '1,3 s/(20[0-9]{2})(\s*[\w.])/\1 - '$cur_year'\2/g' $file

	        	exit_status=$?
		fi
		git add $file
	fi

done

echo "'Copyright' has been changed to actual ($cur_year)"
echo
#exit 0
